
GET http://localhost:3000


### ❗❗❗❗❗ AUTH
GET http://localhost:3000/auth/session


### 📩 📩 📩 SURAT KELUAR

GET http://localhost:3000/outbox/update

###

GET http://localhost:3000/outbox/get


### 🖨️ 🖨️ 🖨️ SCAN DOKUMEN

GET http://localhost:3000/docvault/update

###

GET http://localhost:3000/docvault/get