
# @no-cookie-jar
GET http://localhost:3000
Cookie: session_token=817931767|sess:5224f6a1-68c5-490f-8976-c941f30da00b

### ❗❗❗❗❗ AUTH
POST http://localhost:3000/auth/login
content-type: application/json

{
    "nip": "817931767",
    "password": "767"
}


###

# @no-cookie-jar
GET http://localhost:3000/auth/session
Cookie: session_token=817931767|sess:5224f6a1-68c5-490f-8976-c941f30da00b

### 📩 📩 📩 OUTBOX / SURAT KELUAR

GET http://localhost:3000/outbox/update

Cookie: session_token=abc12345; user_pref=darkmode

###

GET http://localhost:3000/outbox/get


### 🖨️ 🖨️ 🖨️ DOCVAULT / SCAN DOKUMEN

GET http://localhost:3000/docvault/update

###

GET http://localhost:3000/docvault/get


### GET NPWP ⚡⚡
GET http://localhost:3000/mfwp/get/010000131217002